--
-- PostgreSQL database dump
--

\restrict vEmKqecg19tQ8IKzkKKA8ukguDjgxNY7Xd2qeH66heBa1FCaNcH5OQDXAYdhPoc

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

-- Started on 2025-11-29 18:17:56 +03

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE IF EXISTS "concerts and rehearsals";
--
-- TOC entry 3553 (class 1262 OID 16388)
-- Name: concerts and rehearsals; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE "concerts and rehearsals" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'C.UTF-8';


ALTER DATABASE "concerts and rehearsals" OWNER TO postgres;

\unrestrict vEmKqecg19tQ8IKzkKKA8ukguDjgxNY7Xd2qeH66heBa1FCaNcH5OQDXAYdhPoc
\encoding SQL_ASCII
\connect -reuse-previous=on "dbname='concerts and rehearsals'"
\restrict vEmKqecg19tQ8IKzkKKA8ukguDjgxNY7Xd2qeH66heBa1FCaNcH5OQDXAYdhPoc

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 223 (class 1259 OID 16425)
-- Name: band_membership; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.band_membership (
    band_id integer NOT NULL,
    musician_id integer NOT NULL,
    join_date date DEFAULT CURRENT_DATE NOT NULL,
    CONSTRAINT join_date_check CHECK ((join_date <= CURRENT_DATE))
);


ALTER TABLE public.band_membership OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16397)
-- Name: bands; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.bands (
    band_id integer NOT NULL,
    band_name character varying(100) NOT NULL,
    genre character varying(50),
    founded_date date DEFAULT CURRENT_DATE NOT NULL,
    CONSTRAINT founded_date_check CHECK ((founded_date <= CURRENT_DATE)),
    CONSTRAINT genre_check CHECK (((genre)::text = ANY ((ARRAY['rock'::character varying, 'pop'::character varying, 'jazz'::character varying, 'blues'::character varying, 'classical'::character varying, 'electronic'::character varying, 'folk'::character varying, 'metal'::character varying, 'punk'::character varying, 'reggae'::character varying, 'hip-hop'::character varying, 'country'::character varying, 'funk'::character varying, 'soul'::character varying, 'r&b'::character varying, 'alternative'::character varying, 'indie'::character varying, 'hard_rock'::character varying, 'progressive'::character varying, 'house'::character varying, 'techno'::character varying])::text[])))
);


ALTER TABLE public.bands OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 16521)
-- Name: bands_band_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.bands ALTER COLUMN band_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bands_band_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16403)
-- Name: concerts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.concerts (
    concert_id integer NOT NULL,
    concert_title character varying(200) NOT NULL,
    venue_address character varying(255) NOT NULL,
    concert_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.concerts OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16522)
-- Name: concerts_concert_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.concerts ALTER COLUMN concert_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.concerts_concert_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16389)
-- Name: musicians; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.musicians (
    musician_id integer CONSTRAINT musician_musician_id_not_null NOT NULL,
    first_name character varying(50) CONSTRAINT musician_first_name_not_null NOT NULL,
    last_name character varying(50) CONSTRAINT musician_last_name_not_null NOT NULL,
    phone character varying(20) CONSTRAINT musician_phone_not_null NOT NULL,
    telegram character varying(100),
    instrument character varying(50) CONSTRAINT musician_instrument_not_null NOT NULL,
    CONSTRAINT instrument_check CHECK (((instrument)::text = ANY ((ARRAY['guitar'::character varying, 'bass'::character varying, 'drums'::character varying, 'keyboards'::character varying, 'piano'::character varying, 'vocals'::character varying, 'violin'::character varying, 'cello'::character varying, 'trumpet'::character varying, 'saxophone'::character varying, 'trombone'::character varying, 'flute'::character varying, 'clarinet'::character varying, 'accordion'::character varying, 'harp'::character varying])::text[]))),
    CONSTRAINT phone_check CHECK (((phone)::text ~~ '^\+375[0-9]{9}$'::text)),
    CONSTRAINT telegram_check CHECK (((telegram)::text ~~ '@%'::text))
);


ALTER TABLE public.musicians OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16520)
-- Name: musicians_musician_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.musicians ALTER COLUMN musician_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.musicians_musician_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16432)
-- Name: performances; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.performances (
    performance_id integer NOT NULL,
    band_id integer NOT NULL,
    concert_id integer NOT NULL,
    performance_order integer,
    CONSTRAINT performance_order_check CHECK ((performance_order > 0))
);


ALTER TABLE public.performances OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16524)
-- Name: performances_performance_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.performances ALTER COLUMN performance_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.performances_performance_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16410)
-- Name: rehearsals; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rehearsals (
    rehearsal_id integer NOT NULL,
    band_id integer NOT NULL,
    rehearsal_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    duration_minutes integer,
    location character varying(255) NOT NULL,
    CONSTRAINT duration_minutes_check CHECK ((duration_minutes > 0))
);


ALTER TABLE public.rehearsals OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 16523)
-- Name: rehearsals_rehearsal_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.rehearsals ALTER COLUMN rehearsal_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rehearsals_rehearsal_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3541 (class 0 OID 16425)
-- Dependencies: 223
-- Data for Name: band_membership; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.band_membership (band_id, musician_id, join_date) FROM stdin;
\.


--
-- TOC entry 3538 (class 0 OID 16397)
-- Dependencies: 220
-- Data for Name: bands; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.bands (band_id, band_name, genre, founded_date) FROM stdin;
\.


--
-- TOC entry 3539 (class 0 OID 16403)
-- Dependencies: 221
-- Data for Name: concerts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.concerts (concert_id, concert_title, venue_address, concert_date) FROM stdin;
\.


--
-- TOC entry 3537 (class 0 OID 16389)
-- Dependencies: 219
-- Data for Name: musicians; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.musicians (musician_id, first_name, last_name, phone, telegram, instrument) FROM stdin;
\.


--
-- TOC entry 3542 (class 0 OID 16432)
-- Dependencies: 224
-- Data for Name: performances; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.performances (performance_id, band_id, concert_id, performance_order) FROM stdin;
\.


--
-- TOC entry 3540 (class 0 OID 16410)
-- Dependencies: 222
-- Data for Name: rehearsals; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.rehearsals (rehearsal_id, band_id, rehearsal_date, duration_minutes, location) FROM stdin;
\.


--
-- TOC entry 3554 (class 0 OID 0)
-- Dependencies: 226
-- Name: bands_band_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.bands_band_id_seq', 1, false);


--
-- TOC entry 3555 (class 0 OID 0)
-- Dependencies: 227
-- Name: concerts_concert_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.concerts_concert_id_seq', 1, false);


--
-- TOC entry 3556 (class 0 OID 0)
-- Dependencies: 225
-- Name: musicians_musician_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.musicians_musician_id_seq', 1, false);


--
-- TOC entry 3557 (class 0 OID 0)
-- Dependencies: 229
-- Name: performances_performance_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.performances_performance_id_seq', 1, false);


--
-- TOC entry 3558 (class 0 OID 0)
-- Dependencies: 228
-- Name: rehearsals_rehearsal_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.rehearsals_rehearsal_id_seq', 1, false);


--
-- TOC entry 3382 (class 2606 OID 16431)
-- Name: band_membership band_membership_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.band_membership
    ADD CONSTRAINT band_membership_pkey PRIMARY KEY (band_id, musician_id);


--
-- TOC entry 3371 (class 2606 OID 16421)
-- Name: bands bands_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bands
    ADD CONSTRAINT bands_pkey PRIMARY KEY (band_id);


--
-- TOC entry 3375 (class 2606 OID 16419)
-- Name: concerts concerts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.concerts
    ADD CONSTRAINT concerts_pkey PRIMARY KEY (concert_id);


--
-- TOC entry 3367 (class 2606 OID 16485)
-- Name: musicians musician_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.musicians
    ADD CONSTRAINT musician_pkey PRIMARY KEY (musician_id);


--
-- TOC entry 3384 (class 2606 OID 16439)
-- Name: performances performances_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.performances
    ADD CONSTRAINT performances_pkey PRIMARY KEY (performance_id);


--
-- TOC entry 3380 (class 2606 OID 16415)
-- Name: rehearsals rehearsals_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rehearsals
    ADD CONSTRAINT rehearsals_pkey PRIMARY KEY (rehearsal_id);


--
-- TOC entry 3369 (class 2606 OID 16483)
-- Name: musicians unphone; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.musicians
    ADD CONSTRAINT unphone UNIQUE (phone);


--
-- TOC entry 3372 (class 1259 OID 16510)
-- Name: idx_bands_band_name; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_bands_band_name ON public.bands USING btree (band_name varchar_ops) WITH (deduplicate_items='true');


--
-- TOC entry 3373 (class 1259 OID 16511)
-- Name: idx_bands_genre; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_bands_genre ON public.bands USING btree (genre varchar_ops) WITH (deduplicate_items='true');


--
-- TOC entry 3376 (class 1259 OID 16517)
-- Name: idx_concerts_concert_title; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_concerts_concert_title ON public.concerts USING btree (concert_title varchar_ops) WITH (deduplicate_items='true');


--
-- TOC entry 3377 (class 1259 OID 16518)
-- Name: idx_concerts_venue_address; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_concerts_venue_address ON public.concerts USING btree (venue_address varchar_ops) WITH (deduplicate_items='true');


--
-- TOC entry 3362 (class 1259 OID 16516)
-- Name: idx_musicians_full_name; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_musicians_full_name ON public.musicians USING btree (last_name varchar_ops, first_name varchar_ops) WITH (deduplicate_items='true');


--
-- TOC entry 3363 (class 1259 OID 16513)
-- Name: idx_musicians_instrument; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_musicians_instrument ON public.musicians USING btree (instrument varchar_ops) WITH (deduplicate_items='true');


--
-- TOC entry 3364 (class 1259 OID 16512)
-- Name: idx_musicians_last_name; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_musicians_last_name ON public.musicians USING btree (last_name varchar_ops) WITH (deduplicate_items='true');


--
-- TOC entry 3365 (class 1259 OID 16514)
-- Name: idx_musicians_phone; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX idx_musicians_phone ON public.musicians USING btree (phone varchar_ops) WITH (deduplicate_items='true');


--
-- TOC entry 3378 (class 1259 OID 16519)
-- Name: idx_rehearsals_location; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_rehearsals_location ON public.rehearsals USING btree (location varchar_ops) WITH (deduplicate_items='true');


--
-- TOC entry 3386 (class 2606 OID 16458)
-- Name: band_membership band_membership_band_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.band_membership
    ADD CONSTRAINT band_membership_band_id_fk FOREIGN KEY (band_id) REFERENCES public.bands(band_id);


--
-- TOC entry 3387 (class 2606 OID 16487)
-- Name: band_membership band_membership_musician_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.band_membership
    ADD CONSTRAINT band_membership_musician_id_fk FOREIGN KEY (musician_id) REFERENCES public.musicians(musician_id);


--
-- TOC entry 3388 (class 2606 OID 16468)
-- Name: performances performances_band_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.performances
    ADD CONSTRAINT performances_band_id_fk FOREIGN KEY (band_id) REFERENCES public.bands(band_id);


--
-- TOC entry 3389 (class 2606 OID 16473)
-- Name: performances performances_concert_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.performances
    ADD CONSTRAINT performances_concert_id_fk FOREIGN KEY (concert_id) REFERENCES public.concerts(concert_id);


--
-- TOC entry 3385 (class 2606 OID 16453)
-- Name: rehearsals rehearsals_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rehearsals
    ADD CONSTRAINT rehearsals_fk FOREIGN KEY (band_id) REFERENCES public.bands(band_id);


-- Completed on 2025-11-29 18:17:56 +03

--
-- PostgreSQL database dump complete
--

\unrestrict vEmKqecg19tQ8IKzkKKA8ukguDjgxNY7Xd2qeH66heBa1FCaNcH5OQDXAYdhPoc

